# -*- coding: utf-8 -*-
"""EfficientNet+GCN+Unseen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MijPVXcdJv85E6YETgN4ui9-FLgx7PC_

# =============================
# 1) Setup
# =============================
"""

from google.colab import drive
import os
import subprocess
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
from torchvision import models, transforms

"""# Install PyG in a fresh runtime"""

subprocess.run(["pip", "-q", "install", "torch-geometric"], check=True)

from torch_geometric.nn import GCNConv
from torch_geometric.data import Data
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import classification_report, confusion_matrix

drive.mount('/content/drive')

# ===== EDIT PATHS =====
DATASET_ZIP = "/content/drive/MyDrive/PhD/DataSets/dataset_split.zip"
DATASET_ROOT = "/content/content/dataset_split"
UNSEEN_ROOT = "/content/unseen_images"  # class-wise folders
UNSEEN_ZIP = "/content/drive/MyDrive/PhD/DataSets/unseen_images.zip"  # folder with class subfolders
TRAIN_ROOT = "/content/content/dataset_split/train"  # used to preserve label order
EMBEDDING_DIM = 256
HIDDEN_DIM = 512
EPOCHS = 200
# ======================

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", DEVICE)

"""# Unzipping Data"""

if not os.path.exists(DATASET_ROOT):
    import subprocess
    subprocess.run(["unzip", "-q", DATASET_ZIP, "-d", "/content/"], check=True)
    print(f"Unzipped dataset into: {DATASET_ROOT}")
else:
    print(f"Dataset already exists at: {DATASET_ROOT}")

for split in ["train", "val", "test"]:
    split_path = os.path.join(DATASET_ROOT, split)
    print(split, "exists:", os.path.isdir(split_path))

"""# Unzipping Unseen"""

if not os.path.exists("/content/content/unseen"):
    import subprocess
    subprocess.run(["unzip", "-q", UNSEEN_ZIP, "-d", "/content/"], check=True)
    print("Unzipped dataset into: /content/content/unseen")
else:
    print("Dataset already exists at: /content/content/unseen")

"""# =============================
# 2) Match training GCN architecture
# =============================
"""

class GCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, embedding_channels, dropout=0.5):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        # (b) modified GCN output: refined embeddings, not class logits
        self.conv3 = GCNConv(hidden_channels, embedding_channels)
        self.dropout = dropout

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        x = self.conv3(x, edge_index)
        return x


# (a) new ArcFace module
class ArcFaceLoss(nn.Module):
    def __init__(self, embedding_dim, num_classes, scale=30.0, margin=0.5):
        super().__init__()
        self.weight = nn.Parameter(torch.empty(num_classes, embedding_dim))
        nn.init.xavier_uniform_(self.weight)
        self.scale = scale
        self.margin = margin
        self.cos_m = math.cos(margin)
        self.sin_m = math.sin(margin)
        self.th = math.cos(math.pi - margin)
        self.mm = math.sin(math.pi - margin) * margin

    def logits(self, embeddings):
        embeddings = F.normalize(embeddings, p=2, dim=1)
        weights = F.normalize(self.weight, p=2, dim=1)
        return F.linear(embeddings, weights) * self.scale

    def forward(self, embeddings, labels):
        embeddings = F.normalize(embeddings, p=2, dim=1)
        weights = F.normalize(self.weight, p=2, dim=1)
        cosine = F.linear(embeddings, weights).clamp(-1.0 + 1e-7, 1.0 - 1e-7)
        sine = torch.sqrt(1.0 - torch.pow(cosine, 2))
        phi = cosine * self.cos_m - sine * self.sin_m
        phi = torch.where(cosine > self.th, phi, cosine - self.mm)

        one_hot = F.one_hot(labels, num_classes=self.weight.size(0)).float()
        logits = (one_hot * phi) + ((1.0 - one_hot) * cosine)
        logits = logits * self.scale
        return F.cross_entropy(logits, labels), logits

"""
# =============================
# 3) Build class mapping (must match training)
# ============================="""

def build_class_mapping(train_root: str, unseen_root: str):
    if os.path.isdir(train_root):
        class_names = sorted([
            d for d in os.listdir(train_root)
            if os.path.isdir(os.path.join(train_root, d))
        ])
        print("Using class order from TRAIN_ROOT")
    else:
        class_names = sorted([
            d for d in os.listdir(unseen_root)
            if os.path.isdir(os.path.join(unseen_root, d))
        ])
        print("WARNING: TRAIN_ROOT was not found.")
        print("Using class order from UNSEEN_ROOT; ensure this matches training order.")

    class_to_idx = {cls: i for i, cls in enumerate(class_names)}
    return class_names, class_to_idx


class_names, class_to_idx = build_class_mapping(TRAIN_ROOT, UNSEEN_ROOT)
num_classes = len(class_names)
print("Num classes:", num_classes)

"""# =============================
# 4) EfficientNet-B0 feature extractor
# =============================
"""

feature_model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1)
feature_model.classifier = nn.Identity()  # 1280-d embedding
feature_model = feature_model.to(DEVICE)
feature_model.eval()

feature_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

def extract_split_embeddings(split_dir: str, model, transform, device, class_to_idx):
    embeddings, labels, paths = [], [], []

    for cls_name in sorted(os.listdir(split_dir)):
        cls_dir = os.path.join(split_dir, cls_name)
        if not os.path.isdir(cls_dir):
            continue

        if cls_name not in class_to_idx:
            print(f"Skipping class '{cls_name}' (not present in class list)")
            continue

        for fname in tqdm(sorted(os.listdir(cls_dir)), desc=f"Extracting {os.path.basename(split_dir)}:{cls_name}"):
            if not fname.lower().endswith((".jpg", ".jpeg", ".png")):
                continue

            img_path = os.path.join(cls_dir, fname)
            try:
                img = Image.open(img_path).convert("RGB")
                x = transform(img).unsqueeze(0).to(device)
                with torch.no_grad():
                    feat = model(x)
                embeddings.append(feat.squeeze().cpu().numpy())
                labels.append(class_to_idx[cls_name])
                paths.append(img_path)
            except Exception as e:
                print(f"Skipping {img_path}: {e}")

    return (
        np.array(embeddings, dtype=np.float32),
        np.array(labels, dtype=np.int64),
        np.array(paths),
    )


def extract_unseen_embeddings(unseen_root: str, model, transform, device, class_to_idx):
    embeddings, labels, paths = [], [], []

    for cls_name in sorted(os.listdir(unseen_root)):
        cls_dir = os.path.join(unseen_root, cls_name)
        if not os.path.isdir(cls_dir):
            continue

        if cls_name not in class_to_idx:
            print(f"Skipping class '{cls_name}' (not present in training class list)")
            continue

        for fname in tqdm(sorted(os.listdir(cls_dir)), desc=f"Extracting {cls_name}"):
            if not fname.lower().endswith((".jpg", ".jpeg", ".png")):
                continue

            img_path = os.path.join(cls_dir, fname)
            try:
                img = Image.open(img_path).convert("RGB")
                x = transform(img).unsqueeze(0).to(device)
                with torch.no_grad():
                    feat = model(x)
                embeddings.append(feat.squeeze().cpu().numpy())
                labels.append(class_to_idx[cls_name])
                paths.append(img_path)
            except Exception as e:
                print(f"Skipping {img_path}: {e}")

    return (
        np.array(embeddings, dtype=np.float32),
        np.array(labels, dtype=np.int64),
        np.array(paths),
    )


"""# =============================
# 5) Train fresh GCN + ArcFace head
# =============================
"""

def build_knn_edge_index(features: np.ndarray, k: int = 10):
    k = min(k, len(features) - 1)
    if k < 1:
        raise ValueError("Need at least 2 images to build a kNN graph.")

    nbrs = NearestNeighbors(n_neighbors=k + 1, metric="cosine")
    nbrs.fit(features)
    _, indices = nbrs.kneighbors(features)

    src, dst = [], []
    for i in range(indices.shape[0]):
        for j in indices[i, 1:]:
            src.append(i)
            dst.append(int(j))
            src.append(int(j))
            dst.append(i)

    return np.vstack([src, dst])


def accuracy(logits, labels):
    pred = logits.argmax(dim=1)
    return (pred == labels).float().mean().item()


def evaluate_training_graph(model, criterion, data, mask):
    model.eval()
    criterion.eval()
    with torch.no_grad():
        embeddings = model(data.x, data.edge_index)
        loss, logits = criterion(embeddings[mask], data.y[mask])
        acc = accuracy(logits, data.y[mask])
    return loss.item(), acc


train_dir = os.path.join(DATASET_ROOT, "train")
val_dir = os.path.join(DATASET_ROOT, "val")

X_train, y_train, paths_train = extract_split_embeddings(
    train_dir, feature_model, feature_transform, DEVICE, class_to_idx
)
X_val, y_val, paths_val = extract_split_embeddings(
    val_dir, feature_model, feature_transform, DEVICE, class_to_idx
)

assert len(X_train) > 1, "Need at least 2 train images to build a training graph."
assert len(X_val) > 0, "Need at least 1 validation image."

X_train_graph = np.vstack([X_train, X_val]).astype(np.float32)
y_train_graph = np.concatenate([y_train, y_val]).astype(np.int64)
edge_index_train_np = build_knn_edge_index(X_train_graph, k=10)

train_mask = torch.zeros(len(X_train_graph), dtype=torch.bool)
val_mask = torch.zeros(len(X_train_graph), dtype=torch.bool)
train_mask[:len(X_train)] = True
val_mask[len(X_train):] = True

data_train = Data(
    x=torch.tensor(X_train_graph, dtype=torch.float32),
    edge_index=torch.tensor(edge_index_train_np, dtype=torch.long),
    y=torch.tensor(y_train_graph, dtype=torch.long),
    train_mask=train_mask,
    val_mask=val_mask,
).to(DEVICE)

gcn_model = GCN(
    in_channels=data_train.x.shape[1],
    hidden_channels=HIDDEN_DIM,
    embedding_channels=EMBEDDING_DIM,
    dropout=0.5,
).to(DEVICE)
criterion = ArcFaceLoss(embedding_dim=EMBEDDING_DIM, num_classes=num_classes, scale=30.0, margin=0.5).to(DEVICE)

optimizer = torch.optim.Adam(
    list(gcn_model.parameters()) + list(criterion.parameters()),
    lr=1e-3,
    weight_decay=5e-4,
)

best_val_acc = 0.0
history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}

for epoch in range(1, EPOCHS + 1):
    gcn_model.train()
    criterion.train()
    optimizer.zero_grad()

    embeddings = gcn_model(data_train.x, data_train.edge_index)
    loss, train_logits = criterion(embeddings[data_train.train_mask], data_train.y[data_train.train_mask])
    loss.backward()
    optimizer.step()

    train_acc = accuracy(train_logits, data_train.y[data_train.train_mask])
    val_loss, val_acc = evaluate_training_graph(gcn_model, criterion, data_train, data_train.val_mask)

    history["train_loss"].append(loss.item())
    history["train_acc"].append(train_acc)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)
    best_val_acc = max(best_val_acc, val_acc)

    if epoch % 10 == 0 or epoch == 1:
        print(
            f"Epoch {epoch:03d} | "
            f"Train Loss {loss.item():.4f} | Train Acc {train_acc:.4f} | "
            f"Val Loss {val_loss:.4f} | Val Acc {val_acc:.4f}"
        )

print("Best Val Acc:", best_val_acc)

"""# =============================
# 6) Build unseen graph (kNN)
# =============================
"""

X_unseen, y_unseen, paths_unseen = extract_unseen_embeddings(
    UNSEEN_ROOT, feature_model, feature_transform, DEVICE, class_to_idx
)
print("Unseen embeddings shape:", X_unseen.shape)
print("Unseen labels shape:", y_unseen.shape)

assert len(X_unseen) > 1, "Need at least 2 unseen images to build a kNN graph."

edge_index_np = build_knn_edge_index(X_unseen, k=10)
print("edge_index shape:", edge_index_np.shape)

x_tensor = torch.tensor(X_unseen, dtype=torch.float32)
y_tensor = torch.tensor(y_unseen, dtype=torch.long)
edge_index = torch.tensor(edge_index_np, dtype=torch.long)

data_unseen = Data(x=x_tensor, edge_index=edge_index, y=y_tensor).to(DEVICE)

"""# =============================
# 7) Evaluate unseen accuracy with freshly trained model
# =============================
"""

gcn_model.eval()
criterion.eval()

with torch.no_grad():
    embeddings = gcn_model(data_unseen.x, data_unseen.edge_index)
    logits = criterion.logits(embeddings)

pred = logits.argmax(dim=1).cpu().numpy()
true = data_unseen.y.cpu().numpy()

unseen_acc = (pred == true).mean()
print(f"\nUnseen Accuracy (GCN on EfficientNet-B0 embeddings): {unseen_acc:.4f}")

present_labels = sorted(np.unique(true).tolist())
present_names = [class_names[i] for i in present_labels]

print("\nClassification Report (Unseen):")
print(classification_report(
    true,
    pred,
    labels=present_labels,
    target_names=present_names,
    digits=4,
    zero_division=0,
))

cm = confusion_matrix(true, pred, labels=present_labels)
plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=present_names,
    yticklabels=present_names,
)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - Unseen Data (EfficientNet-B0 + GCN)")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# Optional: inspect some predictions
print("\nSample predictions:")
for i in range(min(10, len(paths_unseen))):
    print(f"{i:03d}: true={class_names[true[i]]}, pred={class_names[pred[i]]}, path={paths_unseen[i]}")
