# -*- coding: utf-8 -*-
"""PhD_EfficientNetB0_GCN_Exp_V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPXNQppuWUiDgsnVVep3N3I0Tup6Zykx

# # 1) Setup & Google Drive
"""

from google.colab import drive
import os
import shutil
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

drive.mount('/content/drive')# # 1) Setup & Google Drive

DATASET_ZIP = "/content/drive/MyDrive/PhD/DataSets/dataset_split.zip"
DATASET_ROOT = "/content/content/dataset_split"
EMBED_SAVE_DIR = "/content/embeddings_efficientnetb0_gcn"
EMBED_DRIVE_DIR = "/content/drive/MyDrive/PhD/PhD_EfficientNetB0_GCN_Exp_V1/embeddings_train_val_test"
MODEL_SAVE_PATH = "/content/best_gcn_from_efficientnetb0.pth"
MODEL_DRIVE_PATH = "/content/drive/MyDrive/PhD/PhD_EfficientNetB0_GCN_Exp_V1/best_gcn_from_efficientnetb0.pth"

print("Setup complete.")

"""# # 2) Unzip dataset (run once)"""

if not os.path.exists(DATASET_ROOT):
    import subprocess
    subprocess.run(["unzip", "-q", DATASET_ZIP, "-d", "/content/"], check=True)
    print(f"Unzipped dataset into: {DATASET_ROOT}")
else:
    print(f"Dataset already exists at: {DATASET_ROOT}")

for split in ["train", "val", "test"]:
    split_path = os.path.join(DATASET_ROOT, split)
    print(split, "exists:", os.path.isdir(split_path))

"""# # 3) Install graph library (PyTorch Geometric)"""

import subprocess
subprocess.run(["pip", "-q", "install", "torch-geometric"], check=True)
print("torch-geometric installed.")

"""# # 4) Build EfficientNet-B0 feature extractor"""

import torch
import torch.nn as nn
from torchvision import models, transforms
from tqdm import tqdm

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", DEVICE)

feature_model = models.efficientnet_b0(pretrained=True)
feature_model.classifier = nn.Identity()  # use penultimate embedding
feature_model = feature_model.to(DEVICE)
feature_model.eval()

feature_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

"""# # 5) Extract embeddings for train/val/test
# Skip if you already have `.npy` files.

"""

def extract_embeddings(split_dir: str, model, transform, device):
    classes = sorted([d for d in os.listdir(split_dir) if os.path.isdir(os.path.join(split_dir, d))])
    class_to_idx = {name: i for i, name in enumerate(classes)}

    embeddings, labels, paths = [], [], []

    for cls in classes:
        cls_dir = os.path.join(split_dir, cls)
        files = sorted(os.listdir(cls_dir))
        for fname in tqdm(files, desc=f"Extracting {os.path.basename(split_dir)}:{cls}"):
            if not fname.lower().endswith((".jpg", ".jpeg", ".png")):
                continue

            img_path = os.path.join(cls_dir, fname)
            try:
                img = Image.open(img_path).convert("RGB")
                x = transform(img).unsqueeze(0).to(device)
                with torch.no_grad():
                    feat = model(x)
                embeddings.append(feat.squeeze().cpu().numpy())
                labels.append(class_to_idx[cls])
                paths.append(img_path)
            except Exception as e:
                print(f"Skipping {img_path}: {e}")

    return np.array(embeddings), np.array(labels), np.array(paths), classes


def save_split_embeddings(save_root: str, split: str, embeddings, labels, paths):
    os.makedirs(save_root, exist_ok=True)
    np.save(os.path.join(save_root, f"embeddings_{split}_efficientnet_b0.npy"), embeddings)
    np.save(os.path.join(save_root, f"labels_{split}_efficientnet_b0.npy"), labels)
    np.save(os.path.join(save_root, f"image_paths_{split}_efficientnet_b0.npy"), paths)
    print(f"Saved split={split} into {save_root}")


for split in ["train", "val", "test"]:
    split_dir = os.path.join(DATASET_ROOT, split)
    emb, lbl, pth, classes = extract_embeddings(split_dir, feature_model, feature_transform, DEVICE)
    save_split_embeddings(EMBED_SAVE_DIR, split, emb, lbl, pth)
    print(split, emb.shape)

"""# # 6) (Alternative) Copy precomputed embeddings from Drive

"""

if not os.path.exists(EMBED_SAVE_DIR):
    shutil.copytree(EMBED_DRIVE_DIR, EMBED_SAVE_DIR)
    print("Copied embeddings from Drive.")
else:
    print("Local embeddings already exist; skipping copy.")

"""# # 7) Load embeddings and merge all nodes"""

def load_split(split: str):
    e = np.load(os.path.join(EMBED_SAVE_DIR, f"embeddings_{split}_efficientnet_b0.npy"))
    y = np.load(os.path.join(EMBED_SAVE_DIR, f"labels_{split}_efficientnet_b0.npy"))
    p = np.load(os.path.join(EMBED_SAVE_DIR, f"image_paths_{split}_efficientnet_b0.npy"))
    return e, y, p


emb_train, y_train, paths_train = load_split("train")
emb_val, y_val, paths_val = load_split("val")
emb_test, y_test, paths_test = load_split("test")

X = np.vstack([emb_train, emb_val, emb_test]).astype(np.float32)
y = np.concatenate([y_train, y_val, y_test]).astype(np.int64)
all_paths = np.concatenate([paths_train, paths_val, paths_test])

n_train = len(emb_train)
n_val = len(emb_val)
n_test = len(emb_test)

print("Merged X shape:", X.shape)
print("Merged y shape:", y.shape)
print("Split sizes:", n_train, n_val, n_test)

"""# # 8) Build graph edges using kNN over embeddings"""

from sklearn.neighbors import NearestNeighbors

K = 10  # same as ResNet50+GCN
nbrs = NearestNeighbors(n_neighbors=K + 1, metric="cosine")
nbrs.fit(X)
_, indices = nbrs.kneighbors(X)

src, dst = [], []
for i in range(indices.shape[0]):
    for j in indices[i, 1:]:
        src.append(i)
        dst.append(int(j))
        src.append(int(j))
        dst.append(i)

edge_index_np = np.vstack([src, dst])
print("edge_index shape:", edge_index_np.shape)

"""# # 9) Create PyG Data object with train/val/test masks"""

from torch_geometric.data import Data

x_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.long)
edge_index = torch.tensor(edge_index_np, dtype=torch.long)

num_nodes = X.shape[0]
train_mask = torch.zeros(num_nodes, dtype=torch.bool)
val_mask = torch.zeros(num_nodes, dtype=torch.bool)
test_mask = torch.zeros(num_nodes, dtype=torch.bool)

train_mask[:n_train] = True
val_mask[n_train:n_train + n_val] = True
test_mask[n_train + n_val:] = True

data = Data(x=x_tensor, edge_index=edge_index, y=y_tensor,
            train_mask=train_mask, val_mask=val_mask, test_mask=test_mask)

print(data)

"""# # 10) Define GCN model (same params as ResNet50+GCN)"""

from torch_geometric.nn import GCNConv
import torch.nn.functional as F


class GCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, dropout=0.4):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.conv3 = GCNConv(hidden_channels, out_channels)
        self.dropout = dropout

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        x = self.conv3(x, edge_index)
        return x


num_features = data.x.shape[1]
num_classes = int(data.y.max().item() + 1)

gcn_model = GCN(in_channels=num_features, hidden_channels=512, out_channels=num_classes, dropout=0.5).to(DEVICE)
data = data.to(DEVICE)

# same optimizer/lr/wd as ResNet50+GCN
optimizer = torch.optim.Adam(gcn_model.parameters(), lr=1e-3, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

print(gcn_model)

"""# # 11) Train GCN (same epochs as ResNet50+GCN)"""

def accuracy(logits, labels):
    pred = logits.argmax(dim=1)
    return (pred == labels).float().mean().item()


def evaluate(model, data, mask):
    model.eval()
    with torch.no_grad():
        out = model(data.x, data.edge_index)
        loss = criterion(out[mask], data.y[mask]).item()
        acc = accuracy(out[mask], data.y[mask])
    return loss, acc


EPOCHS = 200
best_val_acc = 0.0
history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}

for epoch in range(1, EPOCHS + 1):
    gcn_model.train()
    optimizer.zero_grad()
    out = gcn_model(data.x, data.edge_index)
    loss = criterion(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()

    train_acc = accuracy(out[data.train_mask], data.y[data.train_mask])
    val_loss, val_acc = evaluate(gcn_model, data, data.val_mask)

    history["train_loss"].append(loss.item())
    history["train_acc"].append(train_acc)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(gcn_model.state_dict(), MODEL_SAVE_PATH)

    if epoch % 10 == 0 or epoch == 1:
        print(
            f"Epoch {epoch:03d} | "
            f"Train Loss {loss.item():.4f} | Train Acc {train_acc:.4f} | "
            f"Val Loss {val_loss:.4f} | Val Acc {val_acc:.4f}"
        )

print("Best Val Acc:", best_val_acc)

import shutil

shutil.copy(MODEL_SAVE_PATH,
            MODEL_DRIVE_PATH)

"""# # 12) Load best model (optional: from Drive)"""

os.makedirs("/content/model", exist_ok=True)
local_model_path = "/content/model/best_gcn_from_efficientnetb0.pth"
if os.path.exists(MODEL_SAVE_PATH):
    shutil.copy(MODEL_SAVE_PATH, local_model_path)
    print("Loaded local best model from training run.")
elif os.path.exists(MODEL_DRIVE_PATH):
    shutil.copy(MODEL_DRIVE_PATH, local_model_path)
    print("Copied best model from Drive.")
else:
    print("No trained model found; run training cell first.")

if os.path.exists(local_model_path):
    gcn_model.load_state_dict(torch.load(local_model_path, map_location=DEVICE))
    gcn_model.to(DEVICE)
    gcn_model.eval()

"""# # 13) Test evaluation + confusion matrix"""

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os

# Build class names in label order (same order used during folder-based labeling)
class_names = sorted([
    d for d in os.listdir(os.path.join(DATASET_ROOT, "train"))
    if os.path.isdir(os.path.join(DATASET_ROOT, "train", d))
])

gcn_model.eval()
with torch.no_grad():
    logits = gcn_model(data.x, data.edge_index)

pred_all = logits.argmax(dim=1).cpu().numpy()
true_all = data.y.cpu().numpy()

test_idx = data.test_mask.cpu().numpy()
y_true_test = true_all[test_idx]
y_pred_test = pred_all[test_idx]

test_acc = (y_true_test == y_pred_test).mean()
print(f"Test Accuracy (GCN on EfficientNet embeddings): {test_acc:.4f}")

# Report with labels
print(classification_report(
    y_true_test,
    y_pred_test,
    labels=np.arange(len(class_names)),
    target_names=class_names,
    digits=4,
    zero_division=0
))

# Confusion matrix with class labels on axes
cm = confusion_matrix(y_true_test, y_pred_test, labels=np.arange(len(class_names)))

plt.figure(figsize=(14, 10))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - GCN on EfficientNet Embeddings")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""# # 14) Plot training curves

"""

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history["train_loss"], label="Train Loss")
plt.plot(history["val_loss"], label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("GCN Loss Curves")
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(history["train_acc"], label="Train Acc")
plt.plot(history["val_acc"], label="Val Acc")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("GCN Accuracy Curves")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

"""# # 15) t-SNE of node embeddings (optional visualization)"""

from sklearn.manifold import TSNE

with torch.no_grad():
    x1 = gcn_model.conv1(data.x, data.edge_index)
    x1 = F.relu(x1)
    x2 = gcn_model.conv2(x1, data.edge_index)
    node_repr = F.relu(x2).cpu().numpy()

class_names = sorted([
    d for d in os.listdir(os.path.join(DATASET_ROOT, "train"))
    if os.path.isdir(os.path.join(DATASET_ROOT, "train", d))
])

z2d = TSNE(n_components=2, perplexity=30, random_state=42).fit_transform(node_repr)

plt.figure(figsize=(12, 9))
for class_idx, class_name in enumerate(class_names):
    idx = true_all == class_idx
    if np.sum(idx) == 0:
        continue
    plt.scatter(z2d[idx, 0], z2d[idx, 1], s=8, alpha=0.7, label=class_name)

plt.title("t-SNE of GCN Node Embeddings (EfficientNet-B0 features)")
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8)
plt.tight_layout()
plt.show()

from sklearn.metrics import silhouette_score

test_repr = node_repr[test_mask.cpu().numpy()]
test_labels = true_all[test_mask.cpu().numpy()]

score = silhouette_score(test_repr, test_labels)
print("Test Silhouette Score:", score)

# Centroid map for GCN embeddings using t-SNE
import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

# ---- Required inputs ----
# node_repr   : shape [N, D]   (e.g., penultimate GCN embeddings)
# true_all    : shape [N]      (integer labels for all nodes)
# class_names : list of class names in label index order

num_classes = len(class_names)

# 1) Compute centroid per class
centroids = []
valid_names = []

for i in range(num_classes):
    idx = (true_all == i)
    if np.sum(idx) == 0:
        continue
    centroid = node_repr[idx].mean(axis=0)
    centroids.append(centroid)
    valid_names.append(class_names[i])

centroids = np.array(centroids)
print("Centroids shape:", centroids.shape)  # [num_valid_classes, D]

# 2) 2D projection with t-SNE
perp = min(5, max(2, len(centroids) - 1))
tsne = TSNE(n_components=2, perplexity=perp, random_state=42)
centroids_2d = tsne.fit_transform(centroids)

# 3) Plot centroid map
plt.figure(figsize=(10, 8))

for i, name in enumerate(valid_names):
    x, y = centroids_2d[i]
    plt.scatter(x, y, s=300)
    plt.text(x + 0.1, y + 0.1, name, fontsize=10)

plt.title("Centroid Map in GCN Embedding Space")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.grid(alpha=0.3)
plt.show()

# GCN-based dendrogram using class centroids in GCN embedding space
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, dendrogram

# ---- Required inputs ----
# node_repr   : [N, D]  (GCN embedding for each node, e.g., from penultimate layer)
# true_all    : [N]     (integer class labels for each node)
# class_names : list[str] in label index order
#
# Example:
# with torch.no_grad():
#     x1 = gcn_model.conv1(data.x, data.edge_index)
#     x1 = F.relu(x1)
#     x2 = gcn_model.conv2(x1, data.edge_index)
#     node_repr = F.relu(x2).cpu().numpy()
# true_all = data.y.cpu().numpy()

num_classes = len(class_names)

# 1) Compute class centroids from GCN embeddings
centroids = []
valid_names = []

for i in range(num_classes):
    idx = (true_all == i)
    if np.sum(idx) == 0:
        continue
    centroids.append(node_repr[idx].mean(axis=0))
    valid_names.append(class_names[i])

centroids = np.array(centroids)
print("Centroids shape:", centroids.shape)

# 2) Hierarchical clustering
Z = linkage(centroids, method='ward', metric='euclidean')

# 3) Plot dendrogram
plt.figure(figsize=(14, 6))
dendrogram(
    Z,
    labels=valid_names,
    leaf_rotation=45,
    leaf_font_size=10
)
plt.title("GCN Embedding Dendrogram (Class Centroids)")
plt.xlabel("Classes")
plt.ylabel("Distance")
plt.tight_layout()
plt.show()

# GCN-based image retrieval: query image -> top 5 similar images
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.metrics.pairwise import cosine_similarity

# ---- Required inputs from your GCN pipeline ----
# node_repr        : [N, D] GCN embeddings (e.g., penultimate layer output)
# all_paths        : [N] image paths (train+val+test merged in same order as node_repr)
# true_all         : [N] integer labels for all nodes
# class_names      : list of class names in label order
# data.test_mask   : boolean mask for test nodes (torch tensor)

# Convert test mask to numpy
test_mask_np = data.test_mask.cpu().numpy()
test_indices = np.where(test_mask_np)[0]

# Use only test nodes for retrieval (recommended)
test_embeddings = node_repr[test_indices]
test_paths = all_paths[test_indices]
test_labels = true_all[test_indices]

# Build cosine similarity matrix on test embeddings
sim = cosine_similarity(test_embeddings)

# Pick query index within test set
query_index = 50   # change as needed (0 to len(test_embeddings)-1)

# Rank neighbors
nearest = np.argsort(-sim[query_index])   # descending similarity
nearest = nearest[nearest != query_index] # remove self
nearest = nearest[:5]                     # top 5

# Plot query + neighbors
fig, ax = plt.subplots(1, 6, figsize=(18, 3))

# Query image
ax[0].imshow(Image.open(test_paths[query_index]))
ax[0].set_title(f"Query\n{class_names[test_labels[query_index]]}")
ax[0].axis("off")

# Top-5 similar
for i, n in enumerate(nearest):
    ax[i + 1].imshow(Image.open(test_paths[n]))
    ax[i + 1].set_title(
        f"{class_names[test_labels[n]]}\n(sim={sim[query_index, n]:.3f})",
        fontsize=9
    )
    ax[i + 1].axis("off")

plt.tight_layout()
plt.show()

print("Query Image:", test_paths[query_index])
print("Query Label:", class_names[test_labels[query_index]])

